# Generated by Django 5.2.6 on 2025-09-17 03:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=0, max_digits=10)),
                ('category', models.CharField(choices=[('peralatan', 'Peralatan'), ('pakaian', 'Pakaian'), ('mainan', 'Mainan'), ('panjangan', 'Pajangan'), ('hiasan', 'Hiasan')], default='update', max_length=20)),
                ('image', models.URLField(blank=True, null=True)),
                ('product_views', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('in_stock', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='News',
        ),
    ]
